# Generated by Django 5.1 on 2024-08-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_user_created_at_user_updated_at_alter_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
