# Generated by Django 5.1 on 2024-08-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
