# Generated by Django 5.1 on 2024-08-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0011_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
