# Generated by Django 5.1 on 2024-09-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0019_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('employee', 'Employee')], default='admin', max_length=10),
        ),
    ]
