# Generated by Django 5.1 on 2024-09-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0021_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
