# Generated by Django 5.1 on 2024-09-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0027_products_table_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Users_table',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Products_table',
        ),
    ]
