# Generated by Django 5.1 on 2024-09-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0029_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_table',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('employee', 'Employee')], default='admin', max_length=10),
        ),
    ]
