# Generated by Django 5.1 on 2024-09-22 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0031_products_table_alter_users_table_role_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_table',
            name='employee_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dairy.users_table'),
            preserve_default=False,
        ),
    ]
