# Generated by Django 5.1 on 2024-09-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0032_products_table_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_table',
            name='employee_id',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Products_table',
        ),
    ]
