# Generated by Django 5.1 on 2024-09-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0033_remove_products_table_employee_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users_table',
        ),
    ]
