# Generated by Django 5.1 on 2024-09-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0035_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_table',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('employee', 'Employee')], default='admin', max_length=10),
        ),
    ]
