# Generated by Django 5.1 on 2024-09-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0037_alter_users_table_role_products_table_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_table',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
