# Generated by Django 5.1 on 2024-09-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0038_rename_employee_id_products_table_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_table',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
            preserve_default=False,
        ),
    ]
