# Generated by Django 5.1 on 2024-09-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0040_remove_products_table_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_table',
            name='price',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=10),
            preserve_default=False,
        ),
    ]
