# Generated by Django 5.1 on 2024-09-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0041_products_table_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_table',
            old_name='price',
            new_name='product_price',
        ),
    ]
