# Generated by Django 5.1 on 2024-09-26 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0042_rename_price_products_table_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_table',
            name='product_price',
        ),
    ]
