# Generated by Django 5.1 on 2024-09-30 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0044_products_table_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals_table',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('animal_name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('milk_capacity', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dairy.users_table')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalImages_table',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('animal_image', models.ImageField(upload_to='animal_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dairy.animals_table')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalHealth_table',
            fields=[
                ('health_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkup_date', models.DateField()),
                ('health_status', models.TextField()),
                ('vaccinations', models.CharField(blank=True, max_length=255, null=True)),
                ('treatment_details', models.TextField(blank=True, null=True)),
                ('veterinarian_name', models.CharField(max_length=100)),
                ('next_checkup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dairy.users_table')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='dairy.animals_table')),
            ],
        ),
    ]
