# Generated by Django 5.1 on 2024-09-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0046_rename_animalimages_table_animalimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals_table',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
