# Generated by Django 5.1 on 2024-09-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0047_animals_table_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animals_table',
            old_name='animal_type',
            new_name='animal_category',
        ),
    ]
