# Generated by Django 5.1 on 2024-10-10 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0049_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_table',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.products_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.users_table')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
