# Generated by Django 5.1 on 2024-10-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0050_cart_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_table',
            new_name='Cart',
        ),
    ]
