# Generated by Django 5.1 on 2024-10-14 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0051_rename_cart_table_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_table',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.products_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.users_table')),
            ],
        ),
    ]
