# Generated by Django 5.1 on 2024-10-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0052_feedback_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity_unit',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
