# Generated by Django 5.1 on 2024-10-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0053_cart_quantity_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
