# Generated by Django 5.1 on 2024-10-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0054_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
