# Generated by Django 5.1 on 2024-10-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0056_order_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_table',
        ),
    ]
