# Generated by Django 5.1 on 2024-10-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0058_order_table_orderitem_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
