# Generated by Django 5.1 on 2024-10-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0061_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='date_of_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
