# Generated by Django 5.1 on 2024-10-27 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0062_preorder_date_of_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=255)),
                ('town_city', models.CharField(max_length=50)),
                ('postcode_zip', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.users_table')),
            ],
        ),
    ]
