# Generated by Django 5.1 on 2024-11-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0063_address_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address_table',
            old_name='postcode_zip',
            new_name='pincode',
        ),
    ]
