# Generated by Django 5.1 on 2024-11-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0065_rename_street_address_address_table_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address_table',
            name='town_city',
        ),
    ]
