# Generated by Django 5.1 on 2024-11-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0066_remove_address_table_town_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address_table',
            old_name='district',
            new_name='place',
        ),
    ]
