# Generated by Django 5.1 on 2024-11-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0069_alter_users_table_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_table',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('employee', 'Employee'), ('owner', 'Farm Owner')], max_length=10),
        ),
    ]
