# Generated by Django 5.1 on 2024-11-20 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0070_alter_users_table_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications_table',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dairy.products_table'),
        ),
    ]
