# Generated by Django 5.1 on 2025-01-01 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0072_remove_animals_table_animal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dairy.users_table'),
        ),
    ]
