# Generated by Django 5.1 on 2025-01-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0073_preorder_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preorder',
            old_name='added_by',
            new_name='farmer',
        ),
    ]
