# Generated by Django 5.1 on 2025-01-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0074_rename_added_by_preorder_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
