# Generated by Django 5.1 on 2025-01-08 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0075_preorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='farmer',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dairy.users_table'),
            preserve_default=False,
        ),
    ]
