# Generated by Django 5.1 on 2025-01-08 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0076_alter_preorder_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications_table',
            name='product',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='dairy.products_table'),
            preserve_default=False,
        ),
    ]
