# Generated by Django 5.1 on 2025-01-08 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0077_alter_notifications_table_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications_table',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dairy.products_table'),
        ),
    ]
