# Generated by Django 5.1 on 2025-01-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0079_notifications_table_farmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_table',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
