# Generated by Django 5.1 on 2025-01-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0080_users_table_is_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_table',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('employee', 'DeliveryEmployee'), ('owner', 'Farm Owner')], max_length=10),
        ),
    ]
