# Generated by Django 5.1 on 2025-01-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0082_order_table_assigned_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_table',
            old_name='assigned_employee',
            new_name='deliveryboy',
        ),
    ]
