# Generated by Django 5.1 on 2025-01-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0083_rename_assigned_employee_order_table_deliveryboy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Out', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
