# Generated by Django 5.1 on 2025-02-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0084_alter_order_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_table',
            name='product_subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
