# Generated by Django 5.1 on 2025-02-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0087_alter_order_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash on Delivery'), ('Online Payment', 'Online Payment')], max_length=25),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=25),
        ),
    ]
