# Generated by Django 5.1 on 2025-02-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0088_alter_order_table_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment')], max_length=25),
        ),
    ]
