# Generated by Django 5.1 on 2025-02-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0089_alter_order_table_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Out', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
