# Generated by Django 5.1 on 2025-02-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0091_deliverystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_table',
            name='pincode',
            field=models.CharField(default=686505, max_length=6),
            preserve_default=False,
        ),
    ]
