# Generated by Django 5.1 on 2025-03-10 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0092_users_table_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disease_images/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.users_table')),
            ],
        ),
    ]
