# Generated by Django 5.1 on 2025-03-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0094_alter_diseaseimage_options_diseaseimage_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_table',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
