# Generated by Django 5.1 on 2025-03-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0095_products_table_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('last_paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_paid_date', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.users_table')),
            ],
            options={
                'verbose_name_plural': 'Payment Statuses',
            },
        ),
    ]
